---
all:
  children:
    local_machines:
      hosts:
        local_me:
      vars:
        ansible_host: localhost
        ansible_connection: local
    raspberrypi:
      hosts:
        #mnn_pi:
        #  ansible_host: 10.70.173.xxx
        #myzk_pi:
        #  ansible_host: 10.70.173.xxx
        #nmym_pi:
        #  ansible_host: 10.70.173.xxx
        #nsmr_pi:
        #  ansible_host: 10.70.173.xxx
        yhs_pi:
          ansible_host: 10.70.173.195
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: pi
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_python_interpreter: /usr/bin/python3
    homepi:
      hosts:
        home_pi:
          ansible_host: 192.168.0.88
      vars:
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: pi
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_python_interpreter: /usr/bin/python3

